AWSTemplateFormatVersion: '2010-09-09'
Description: >
    VPC with Two Public Subnets


Parameters:
    VPCName:
        Type: String
        Default: test-vpc-alamin


Mappings:
    CidrBlocks:
        VPC:
            CIDR: '10.0.0.0/16'
        PublicSubnetOne:
            CIDR: '10.0.0.0/24'
        PublicSubnetTwo:
            CIDR: '10.0.1.0/24'


Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: !FindInMap ['CidrBlocks', 'VPC', 'CIDR']
            EnableDnsSupport: 'false'
            EnableDnsHostnames: 'false'
            InstanceTenancy: default
            Tags:
                - Key: Name
                  Value: !Ref 'VPCName'
    
    PublicSubnetOne:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref 'VPC'
            CidrBlock: !FindInMap ['CidrBlocks', 'PublicSubnetOne', 'CIDR']
            AvailabilityZone: 
                Fn::Select:
                    - 0
                    - Fn::GetAZs: {Ref: 'AWS::Region'}
            MapPublicIpOnLaunch: true
    
    PublicSubnetTwo:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref 'VPC'
            CidrBlock: !FindInMap ['CidrBlocks', 'PublicSubnetTwo', 'CIDR']
            AvailabilityZone:
                Fn::Select:
                    - 1
                    - Fn::GetAZs: {Ref: 'AWS::Region'}
            MapPublicIpOnLaunch: true

Outputs:
    VpcId:
        Description: VPC Id
        Value: !Ref 'VPC'
    
    PublicSubnetOne:
        Description: Public Subnet One
        Value: !Ref 'PublicSubnetOne'

    PublicSubnetTwo:
        Description: Public Subnet Two
        Value: !Ref 'PublicSubnetTwo'